"""Add custom frameworks and ownership

Revision ID: b905d9a6c542
Revises: ad8d0fe1c1de
Create Date: 2026-03-21 13:06:52.472417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b905d9a6c542'
down_revision: Union[str, Sequence[str], None] = 'ad8d0fe1c1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frameworks', sa.Column('is_custom', sa.Boolean(), nullable=True))
    # Update existing rows to False
    op.execute("UPDATE frameworks SET is_custom = False")
    # Make it not nullable
    op.alter_column('frameworks', 'is_custom', nullable=False)
    
    op.add_column('frameworks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_frameworks_user_id'), 'frameworks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'frameworks', 'users', ['user_id'], ['id'])
    op.add_column('mitigations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_mitigations_user_id'), 'mitigations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'mitigations', 'users', ['user_id'], ['id'])
    op.add_column('threats', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_threats_user_id'), 'threats', ['user_id'], unique=False)
    op.create_foreign_key(None, 'threats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threats', type_='foreignkey')
    op.drop_index(op.f('ix_threats_user_id'), table_name='threats')
    op.drop_column('threats', 'user_id')
    op.drop_constraint(None, 'mitigations', type_='foreignkey')
    op.drop_index(op.f('ix_mitigations_user_id'), table_name='mitigations')
    op.drop_column('mitigations', 'user_id')
    op.drop_constraint(None, 'frameworks', type_='foreignkey')
    op.drop_index(op.f('ix_frameworks_user_id'), table_name='frameworks')
    op.drop_column('frameworks', 'user_id')
    op.drop_column('frameworks', 'is_custom')
    # ### end Alembic commands ###
